#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9999

#logging.file.name=1.log  # 默认是spring.log
logging:
  file:
    path: logFiles

